version: '3.9'

services:
  db:
    container_name: 't3-db'
    image: postgres:12
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: 't3-db'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}

